Repository Carberra/Carberretta, pull requests merged in 2021-05, with the labels that each got.

#77 Add feeds cog to handle content notifications
  carberretta/bot/cogs/feeds.py
  carberretta/data/static/build.sql
  docker-compose.yml
  poetry.lock
  pyproject.toml
Labels: status/accepted, type/feature

#83 Added Google Command
  carberretta/bot/cogs/links.py
Labels: status/accepted, type/feature

#93 Fix Poll Cache System
  carberretta/bot/cogs/poll.py
Labels: status/accepted, type/feature

#91 Db.py updates
  carberretta/db/db.py
Labels: status/accepted, type/enhancement

#95 optimize database calls in feeds cog
  carberretta/bot/cogs/feeds.py
  carberretta/data/static/build.sql
Labels: status/accepted, type/enhancement

#97 Fixed https://github.com/Carberra/Carberretta/issues/96 and !yt info command
  carberretta/bot/cogs/youtube.py
Labels: status/accepted, type/bug
